### ISSUE TITLE
Title change

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver-webui#9]
I would suggest to stick to repo name
"jmmserver webui" or event "jmmserver-webui-{version_of_webui}"

**Comment by hidden4003** [comment]
I can add version to title, but I don't see why it should look ugly like "jmmserver webui" i.e. lowercase, title is for the user not for us. @ElementalCrisis  any thoughts ?

**Comment by bigretromike** [comment]
Then dont use lowercase, its more of "JMM WEB UI" now ;-) as this is for Server (currently)

**Comment by ElementalCrisis** [comment]
It should look the same as it does in JMM Server and JMM Desktop, "JMM Server Web UI Version X".

**Comment by bigretromike** [comment]
Why you insist to split "web ui" ?

**Comment by ElementalCrisis** [comment]
That's just the way I've seen it written and talked about.

**Comment by hidden4003** [comment]
OK, we need more votes. Server's title is "JMM Server" and desktop is "JMM Desktop" no version in window title. 
Regarding why do I split it just google "webui" you will see that everyone write it like that, the reason is, those are 3 separate words Web User Interface and UI is standard industry term nowadays, but there is no term such as WUI or WebUI, therefore I write it as Web UI.

**Comment by bigretromike** [comment]
Chromium / IBM use WebUI and it looks better, but leave as you like. Just add "server" to it.
